USE online_food
create table onlinefood as select * from online_food_orders_large;   
select * from onlinefood;

/*Question 1: Top Selling Items
SQL Task: Find the top 10 most ordered food items based on quantity sold.*/

SELECT 
    `Item Name`, 
    SUM(Quantity) AS Total_Quantity_Sold
FROM 
    online_food.online_food_orders_large
GROUP BY 
    `Item Name`
ORDER BY 
    Total_Quantity_Sold DESC
LIMIT 10;

/*Question 2: Revenue by Food Category
Goal: Find the total revenue generated by each food category, sorted from highest to lowest.*/
select `Food Category`,SUM(`price`*`Quantity`) as total_revenue from onlinefood
group by `Food Category`
order by total_revenue DESC

/*Question 3: Peak Ordering Hours
Goal: Find out which hours of the day have the highest number of orders.*/
SELECT 
    EXTRACT(HOUR FROM `Order Date & Time`) AS Order_Hour,
    COUNT(`Order ID`) AS Total_Orders
FROM 
    onlinefood
GROUP BY 
    Order_Hour
ORDER BY 
    Total_Orders DESC;

/*Question 4: City-Wise Performance
Goal: Analyze each city by:
Total revenue
Number of orders
Average customer rating */
SELECT 
    City,
    SUM(Quantity * Price) AS Total_Revenue,
    COUNT(`Order ID`) AS Total_Orders,
    AVG(`Customer Rating`) AS Avg_Rating
FROM 
    online_food.online_food_orders_large
GROUP BY 
    City
ORDER BY 
    Total_Revenue DESC;
/*Question 5: Restaurant Performance
Goal: Evaluate restaurants based on:
Total revenue
Number of orders
Average customer rating*/
SELECT `Restaurant Name`,SUM(`Price`*`Quantity`) as Revenue,COUNT(`Order ID`) as Total_Order,AVG(`Customer Rating`) as AVG_Customer_Rating
FROM onlinefood
Group By `Restaurant Name`
Order By Revenue DESC, Total_Order DESC, AVG_Customer_Rating DESC

/*Question 6: Delivery Time Efficiency
Goal: Compare average delivery times across cities and delivery partners to find who delivers fastest.*/
SELECT `Delivery Partner`,`City`,AVG(`Delivery Time (min)`)  as Average_Time
FROM onlinefood
GROUP BY `City`,`Delivery Partner`
ORDER BY Average_Time DESC

/*Question 7: Top 10 Loyal Customers
Goal: Identify the top 10 customers who have placed the most number of orders.*/
SELECT `Customer ID`,COUNT(`Order ID`) as Total_Order
FROM onlinefood
GROUP BY `Customer ID`
ORDER BY Total_Order DESC
LIMIT 10;

/* Question 8: Discounted Revenue Simulation
Goal:
Apply a 10% discount on any order where total revenue > 100, and calculate:
Original revenue
Discounted revenue
Revenue loss */
SELECT `Order ID`,SUM(`price`*`Quantity`) as Revenue,
	SUM(CASE WHEN (`price`*`Quantity`) > 100 THEN (`price`*`Quantity`)*0.9 ELSE (`price`*`Quantity`) END) AS Discounted_Revenue,
    SUM(CASE WHEN (`price`*`Quantity`) > 100 THEN (`price`*`Quantity`)*0.1 ELSE 0 END) AS Revenue_Loss
FROM onlinefood;